{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "poginfo.serviceAccountName" . }}
  labels:
    {{- include "poginfo.labels" . | nindent 4 }}
{{- end -}}
