{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "poginfo.fullname" . }}
  labels:
    {{- include "poginfo.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "poginfo.selectorLabels" . | nindent 6 }}
{{- end }}
